name: Deploy Cookbook to S3

on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - main

env:
  HOME_DIR: /home/ubuntu/prod/cookbook

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END

      - name: Deploy
        env:
          HOME_DIR: ${{ env.HOME_DIR }}
        run: |
          ssh prod "$HOME_DIR/run.sh"
